import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo_Black, Rubik } from "next/font/google";
// import { Archivo_Black } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/sections/Footer";


const archivoBlack = Archivo_Black({
  variable: "--font-archivoBlack",
  subsets: ['latin'],
  weight: ['400'],
})

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{scrollBehavior:'smooth'}}>
      <body
        className={`${archivoBlack.variable} ${geistSans.variable} ${geistMono.variable} ${rubik.variable} 
        font-rubik antialiased  bg-[#0e0e0e] 
        min-h-fit`}
      >
        <Navbar/>
        {children}
        <div id='contact'>
          <Footer/>
        </div>
        
      </body>
    </html>
  );
}
